version: "3.8"

x-custom:
  postgres:
    - &postgres_user "${DATABASE_USERNAME:-postgres}"
    - &postgres_password "${DATABASE_PASSWORD:-password}"

services:
  app:
    image: decidim/decidim:latest
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - node_modules:/app/node_modules
      # exclude volumes
      - /app/vendor
      - /app/tmp
      - /app/log
      - /app/.git
    environment:
      PORT: 3000
      DATABASE_HOST: pg
      DATABASE_USERNAME: *postgres_user
      DATABASE_PASSWORD: *postgres_password
      RAILS_ENV: development
    entrypoint: bundle exec rails s -b 0.0.0.0
    working_dir: /app
    ports:
      - 3000:3000
    links:
      - pg
  pg:
    image: postgres
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: *postgres_user
      POSTGRES_PASSWORD: *postgres_password
    ports:
      - 5433:5432

volumes:
  node_modules: {}
  bundle: {}
  pg-data: {}
